### PR TITLE
[14.0][MIG]document_page_tag

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
supersedes: https://github.com/OCA/knowledge/pull/315

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten

**Review by ivantodorovich — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍 

@etobella could you merge?

**Comment by etobella** [comment]
Habe you signed CLA?

**Comment by ValentinVinagre** [comment]
> Habe you signed CLA?

yes, but there was a problem with the email. We are talking about it to solve it.

**Comment by angelgarciadelachica** [comment]
Hi, yes I did sign the ICLA
I am checking with OCA and they have my correct email and github too, I don't know why the bot detects me with that incorrect email...

**Review by etobella — APPROVED** [review]

**Pull request merged**
