### PR TITLE
[16.0][MIG] document page: Migration to 16.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Review by AntoniRomera — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]
OK

**Comment by FernandoRomera** [comment]
@max3903 Can you relaunch the merge command, please?

**Comment by FernandoRomera** [comment]
@etobella 
It seems to go into a loop with the file document_page.pot. Do you know how to fix it?

[[UPD] Update document_page.pot] (https://github.com/OCA/knowledge/commit/a28169d3b1f4c4abca69c906e36d35366ed4435b)
oca-ci committed 2 minutes ago
 
[[UPD] Update document_page.pot](https://github.com/OCA/knowledge/commit/0b4d2cf5acb80d3b654963159cf3d075645a80a3)
oca-ci committed 3 minutes ago
...

**Comment by etobella** [comment]
Can you remove the file? Just trying something....

**Comment by FernandoRomera** [comment]
@etobella 
Done.

**Comment by FernandoRomera** [comment]
@pedrobaeza
Can you stop the merge and relauch it?.
It has the file document_page.pot in a loop and dont stop.

**Comment by pedrobaeza** [comment]
Well, the POT is needed and it's overwritten each time. Let's try again anyway:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Now the 3 branches keeps generating each time... :scream: 

@sbidoul do you know what's happening with continuous commits of POT update being added to the branch?

**Comment by FernandoRomera** [comment]
@sbidoul @pedrobaeza 
https://github.com/OCA/knowledge/actions
5,098 workflow runs, is there a way to stop them.

**Comment by pedrobaeza** [comment]
I'm not able to do anything, as I don't have access (or don't know how) to reset OCA bot daemon. Let's see if @gurneyalex or @simahawk may, as Stéphane said that he's busy these days.

**Comment by FernandoRomera** [comment]
@pedrobaeza 
Thanks.

**Comment by rousseldenis** [comment]
@FernandoRomera @pedrobaeza But why having removed the pot file ?

**Comment by pedrobaeza** [comment]
It was an attempt to detect the problem, but that's not the question, as both the previous attempts and the one without the POT are in a loop. I have deleted several times the branches, but they get recreated again, so it's the OCA bot that keeps pushing them in a loop. That's why I'm asking to at least recreates them. That may be also the problem for the runboat, creating infinite instances (although not sure if one is created for that temp branch - for me they shouldn't, as they don't bring any value -).

**Comment by etobella** [comment]
I think it has stopped right now

**Comment by pedrobaeza** [comment]
Yeah, it seems so. Let's see if it's due to any manual action by a yet anonymous hero, hehe.

**Comment by etobella** [comment]
Well, I started cancelling all the actions and then bot said something failed.... :thinking:

**Comment by pedrobaeza** [comment]
Let's try again:

/ocabot merge nobump

**Comment by etobella** [comment]
The error happened again :thinking: It might be a problem of some sort because ot the translation changes :thinking:

**Comment by FernandoRomera** [comment]
@etobella 
Do you want me to delete all pot and po files, for testing purposes?

**Comment by etobella** [comment]
I think it is fixed with the last commit from https://github.com/OCA/knowledge/pull/382

Can you take it here and test it :smile:

I was able to reproduce it locally. The problem was related to the en.pot file. That was giving problems. Deleting it fixed it all :smile:

**Comment by pedrobaeza** [comment]
Ouch, how it appeared? That was an old task that removes such file, as indeed it's conflicting.

**Comment by etobella** [comment]
It was introduced on 11.0. I don't know why it didn't fail before

https://github.com/MallorcaSoft/knowledge/commit/125f97d3882bd9bbf3c0a40c9da527f556feba0c#diff-7002718290bb8efb1df8d91551c698f30f23b4fccb0266ef5352073eb3471f07

**Comment by FernandoRomera** [comment]
@etobella @pedrobaeza 
Thank you all for the effort, when you think it is appropriate we could merge this PR.

**Comment by pedrobaeza** [comment]
Replaced by #382 for fixing the problem with en.po.

**Comment by etobella** [comment]
Add the commit please and then we can try

**Comment by pedrobaeza** [comment]
I have already merged your PR, Enric. As it contains this whole story, there's no attribution problem.

**Pull request closed without merging**
