### PR TITLE
[17.0][MIG] document_page_tag: Migration to 17.0

### PR DESCRIPTION
**Pull request by Tisho99**
I have added tag aggrupation because you can group many2many since v16

T-5827

### CODE REVIEW

**Comment by Tisho99** [comment]
@HaraldPanten @ValentinVinagre

**Comment by HaraldPanten** [comment]
> I have added tag aggrupation because you can group many2many since v16
> 
> T-5827

Good job 👍

**Review by HaraldPanten — APPROVED** [review]
Functional review in runboat. LGTM

@etobella

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
