### PR TITLE
[14.0][IMP] document_page: add Browse Wiki Content view Kanban

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago @Matthwhy @WesleyOliveira98 

The purpose of this pull request is to port an existing `Kanban` view related to Browse Wiki Content in v12.0 to v14.0.

### CODE REVIEW

**Review by WesleyOliveira98 — APPROVED** [review]
LGTM

image

**Comment by Matthwhy** [comment]
Functional test
* In Browse wiki content, the Top Level Resources filter has to bring only the registered categories and pull the image registered in these categories (TEST OK)
image

* If you don't fill in the image in the category, you must bring a standard icon (TEST OK)

* Create pages within the category (TEST OK)

image

**Review by Matthwhy — APPROVED** [review]

**Comment by kaynnan** [comment]
ping @OCA/document-maintainers

**Review by max3903 — APPROVED** [review]

**Pull request merged**
