### PR TITLE
[16.0][MIG] document url: Migration to 16.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Review by AntoniRomera — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]
ok

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@FernandoRomera Can you add unit tests to improve codecov results?

**Comment by FernandoRomera** [comment]
@max3903 
Codecov de 86.36 to 92.00
Can you merge this PR, please?

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Comment by Hloul** [comment]
Guys, I downloaded this module from odoo apps but and installed it on v16.
I dont see the button [Attach URL] that used to appear on older versions (i.e. v12)
Back on v12, i see 2 buttons: [Attach File] and [Attach URL].
on v16, the attach icon automatically open a window to choose the file.
You see the attach file button after you attached a first file. But the [attach url] button that is included in this module doesnt ever appear on v16.

any ideas ?

**Comment by rafaelbn** [comment]
@FernandoRomera does this module works for you? It doesn't work as @Hloul says.

GIF 30-06-2023 18-01-47

**Pull request merged**
