### PR TITLE
[13.0][MIG] document_page_portal

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Standard migration

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @OCA/management-systems-maintainers

**Review by rvalyi — APPROVED** [review]
tested on Runbot.

**Comment by marcelsavegnago** [comment]
ping @ivantodorovich

**Review by dreispt — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@etobella can you do merge this PR?

**Comment by marcelsavegnago** [comment]
> /ocabot merge nobump

@etobella thanks 👍

**Pull request merged**
