### PR TITLE
[13.0][MIG] document_page_project

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
Standard document_page_project migration to v13.

cc ~ @ForgeFlow @LoisRForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Comment by AaronHForgeFlow** [comment]
cc @JordiBForgeFlow

**Review by ivantodorovich — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
@JordiBForgeFlow  can you retry?

**Pull request merged**
