### PR TITLE
Fix document_page: Required impossible. Protected method needed

### PR DESCRIPTION
**Pull request by flachica**
Required impossible for type category in document_page
Protected method needed for dependencies

### CODE REVIEW

**Review by ivantodorovich — CHANGES_REQUESTED** [review]
These changes in .pre-commit-config.yaml shouldn't be here, right?
Can you rebase?

**Comment by flachica** [comment]
Oh! Sorry. I still having [this problem](https://github.com/OCA/crm/issues/310) with running pre-commit after installing `python3-setuptools`. I will rebase ASAP.

**Comment by flachica** [comment]
Can you review @ivantodorovich ?

**Review by max3903 — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Review by etobella — APPROVED** [review]
LGTM Join the commits on a single one and we can proceed on the merge :wink:

**Comment by etobella** [comment]
Something is happening with your rebase. Can you try something like:
```
git remote update
git reset origin/13.0 --hard
git cherry-pick 0962bf280cc07b126b7adca9e5cc6e9b5fdd1276
```
Can you check this please?

Do this in a new branch in order to ensure that nothing happens with your original work. If all works as expected you can do it there. I am assuming that origin is the OCA remote

**Comment by flachica** [comment]
I Will do ASAP, this is my first or second PR and has newbie errors. I configurated an linux alias that automatize this and I hope no more error

**Review by marcelsavegnago — APPROVED** [review]

**Comment by flachica** [comment]
@etobella Can you check this changes? Thanks

**Comment by etobella** [comment]
Now it is fine for me, just a comment, I think you have not configured correctly your email on your local git.
Check it with `git config --global user.email` That should be the same email you are using for github.
In order to set it: `git config --global user.email "YOUREMAIL@WHATEVER.COM"`

**Comment by etobella** [comment]
@flachica Could you review how you named the commit and rename it following the guides:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message
https://www.odoo.com/documentation/13.0/reference/guidelines.html#commit-message-structure

Thanks :wink:

**Comment by ivantodorovich** [comment]
What's the status of this? Is it ready to merge?

**Pull request merged**
