### PR TITLE
[ADD] help_popup_document_page

### PR DESCRIPTION
**Pull request by hbrunn**
Document pages for help
=======================

This module knits ``document_page`` and ``help_popup`` together such that you can write your help texts as document pages. The advantage is that you can use your help texts also as (part of) a functional description of your installation, or the other way around.

Installation
============

To install this module, you need to:

#. install ``help_popup`` from the ``web`` repository

Configuration
=============

To configure this module, you need to:

#. add users to the `Documentation writer` or `Advanced documentation writer` group
#. if you're so inclined, provide a template in the document category `Documentation` (added by this module)

Usage
=====

Members of the above mentioned groups will have access to the the fields `Documentation for` and `Advanced documentation for` on a document page *if* the page's category is `Documentation`. In those fields, assign the window action(s) for which the current document page is the (advanced) documentation.

Given you can add multiple document pages as help for the same action (they will be concatenated), you can share writing documentation between multiple people writing about different aspects.

@max3903 @bealdav this is my take on #103

### CODE REVIEW

**Comment by hbrunn** [comment]
travis will be green after merging #130

**Comment by bealdav** [comment]
Really nice @hbrunn thanks a lot for this work.

I've done a PR on help_popup https://github.com/OCA/web/pull/417 but it's not yet merged. I have to fix it.
Do you think it's compatible ?

Thanks again

LGTM, tested, reviewed :+1:

**Comment by hbrunn** [comment]
@bealdav the field names change, but apart from that, this should work. Thanks for your review, but please use the github review workflow instead of the old thumbs up

**Comment by lfreeke** [comment]
:+1: (test)

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
since this is an old PR, could you rebase it to get a fresh CI build?

**Comment by hbrunn** [comment]
yay, somebody looks at my stuff ;-) I squashed commits while being at it

**Pull request merged**
