### PR TITLE
[14.0] [MIG] document_page_group

### PR DESCRIPTION
**Pull request by Du-ma**
Standard migration to 14.0

### CODE REVIEW

**Review by gaikaz — APPROVED** [review]
LGTM

**Review by olgamarcocb — APPROVED** [review]
Locally tested 👍

**Review by AntoniRomera — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by AntoniRomera** [comment]
@Du-ma 
sbidoul commented:
There is currently no way to reinitialize a build (tracked in #34), so you need to push a commit.

**Comment by Du-ma** [comment]
@AntoniRomera
Yahahahaha

**Comment by AntoniRomera** [comment]
@etobella Can you merge this?

**Review by etobella — APPROVED** [review]

**Pull request merged**
