### PR TITLE
[12.0]Multiple UI / UX Improvements 

### PR DESCRIPTION
**Pull request by flotho**

### CODE REVIEW

**Comment by flotho** [comment]
Hi @pedrobaeza @max3903 

I would like to propose some imrpovements for the documentation. This PR is not yet finished but I would like to share with you what I've done.
Our team of dev and not dev user have many troubles to navigate in the pages menu and this was an obstacle for the acceptance of this module.
After many discussion we decided to improve the way we could navigate in the content, and this is the main object of my proposal.
The ideas is to be able to browse easily between category and content in the same view like in simple content management organised in shelves, chapter, pages, etc...

I would like to receive your feedback on this orientation and of course on the code itself.

Thanks in advance for your futures comments

**Comment by pedrobaeza** [comment]
Everything is red, so can't be testable.

**Comment by flotho** [comment]
This time it should be OK.
I tried to add prettier / pylint precommit and all the stuff. It refactored more files than expected, sorry for that.*
Ready for reviews !

**Comment by flotho** [comment]
@pedrobaeza @max3903 you have now something to test, I'll check travis ASAP

**Comment by flotho** [comment]
hummm... it seems that we're facing this kind of issue : https://github.com/odoo/odoo/pull/30881

**Comment by flotho** [comment]
@pedrobaeza @max3903 this one is ready for review, all is green

**Comment by flotho** [comment]
hi @legalsylvain , any review possible here ?

**Comment by legalsylvain** [comment]
I don't use this module. No point of view regarding the changes. 
Note : you have introduced an empty file named "chmod".

**Comment by flotho** [comment]
Hi @yavuzavci , it seems that you haven't signed CLA, any chance to update this ?

Regards

**Comment by flotho** [comment]
yihaaa.... at last everything is green.
Ready for review !

**Comment by pedrobaeza** [comment]
Please summarize the changes in the initial comment + squash commit history merging properly commits. I see that you have made a lot of cosmetic changes that were only warnings, not errors. That's appreciated, but it's convenient to split that ones in a different PR, or at least, commit.

**Comment by flotho** [comment]
@pedrobaeza , ok for explaining, can I keep the "cosmetics changes" in this PR ?

**Comment by pedrobaeza** [comment]
OK as long as you keep it in a separate commit for being discriminated when reviewing the PR. The rest of the changes may go together if the same author or logical set.

**Comment by yavuzavci** [comment]
> Hi @yavuzavci , it seems that you haven't signed CLA, any chance to update this ?
> 
> Regards

Hi,

I've done it as of today. It shouldn't be a problem anymore.

**Comment by flotho** [comment]
close this one in favor of #324

**Pull request closed without merging**
