### PR TITLE
[14.0][IMP] document_page_tag: color_picker widget in color field.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
Improved document_page_tag form view using picker-color widget in color field.

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten @manuelregidor @luis-ron

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@etobella could you merge? a small improvement for a better usability. 👍

**Comment by HaraldPanten** [comment]
THX!

**Pull request merged**
