### PR TITLE
update travis config

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can take the occasion to add Transifex.

**Comment by gurneyalex** [comment]
@pedrobaeza I'm struggling with lack of time atm.

**Comment by dreispt** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@gurneyalex, please merge https://github.com/gurneyalex/knowledge/pull/1 for having Transifex

**Comment by kossovo** [comment]
:+1:

**Pull request merged**
