### PR TITLE
update travis config

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Also add Transifex

**Comment by gurneyalex** [comment]
#62 or #64 for green runbot

**Comment by pedrobaeza** [comment]
I have closed #62 to avoid noise

**Comment by gurneyalex** [comment]
@pedrobaeza no time to play with transifex atm. Sorry.

**Comment by yvaucher** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@gurneyalex, please merge https://github.com/gurneyalex/knowledge/pull/2 for having Transifex

**Pull request merged**
