### PR TITLE
[11.0][IMP] attachment_preview: Split screen

### PR DESCRIPTION
**Pull request by tarteo**
This PR adds a new functionality to the attachment_preview. When you open a preview from the attachments menu in the form view. It opens it in a split screen next to the form view:

image

### CODE REVIEW

**Comment by SalahAdDin** [comment]
It looks very fine!!!

**Comment by pedrobaeza** [comment]
I think this should be configurable, or to have 2 icons: one for seeing it inline and another in the previous new tab behavior.

**Comment by tarteo** [comment]
@pedrobaeza Currently the split screen always opens first. On the split screen there's a button to open it in a new tab. I can add an user preference (like 'Open attachment preview first in split screen') or an extra button to open it directly in a new tab.

**Comment by pedrobaeza** [comment]
Yeah, I didn't want to lose the option to open it in a new tab.

**Comment by tarteo** [comment]
I'll make an user preference. So people who never want to use the split screen can open the attachment in a tab with only one click.

**Review by hbrunn — APPROVED** [review]
cool! I'm just not very good with UI stuff, and am happy when others fix this then. I'll merge after you've rebased

**Comment by SalahAdDin** [comment]
@tarteo Man :+1:

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
Can you rebase to resolve the conflict?

**Comment by tarteo** [comment]
I failed. I'll make a new PR. https://github.com/OCA/knowledge/pull/200

**Pull request closed without merging**
