### PR TITLE
[UPD] Russian translation in 'knowledge' and 'document_page' modules.

### PR DESCRIPTION
**Pull request by SergePogorelov**
Update Russian translations in 'knowledge' and 'document_page' modules.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
Please do the translation via weblate.

**Comment by marcelsavegnago** [comment]
https://translation.odoo-community.org/projects/knowledge-13-0/knowledge-13-0-knowledge

**Comment by SergePogorelov** [comment]
I don't have enough privileges to save translations to weblate.

**Comment by marcelsavegnago** [comment]
> I don't have enough privileges to save translations to weblate.

Try https://odoo-community.org/page/translate

**Comment by SergePogorelov** [comment]
Thanks alot.
Followed your advice.
Added Russian translation to modules 'knowledge' and 'document_page' via weblate.

**Comment by marcelsavegnago** [comment]
> Thanks alot.
> Followed your advice.
> Added Russian translation to modules 'knowledge' and 'document_page' via weblate.

If you need something just let me know and I'll help you.

**Pull request closed without merging**
