### PR TITLE
[15.0][FIX] document_page_group: Issue with logs spamming field error

### PR DESCRIPTION
**Pull request by gabriel-grinspan**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please follow commit message guidelines?

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

**Comment by gabriel-grinspan** [comment]
@pedrobaeza Is this correct now?

**Comment by pedrobaeza** [comment]
I'm afraid the module name is still missing.

**Comment by gabriel-grinspan** [comment]
Please see new commit message.

**Review by pedrobaeza — APPROVED** [review]
Although the module name should be complete, I'm not going to nitpick more, so fast-tracking this for fixing the log warning:

/ocabot merge patch

**Pull request merged**
