### PR TITLE
[12.0][MIG] document_page_reference

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration. Just version bumped, worked without needing other changes.

@etobella @LoisRForgeFlow @AdriaGForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional review :+1:

**Review by etobella — APPROVED** [review]
LGTM :+1: No major changes

**Comment by etobella** [comment]
@OCA/document-maintainers This module is ready for merge

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
