### PR TITLE
document_page_approval porting to 8.0

### PR DESCRIPTION
**Pull request by gborelli**
document_page_approval depends on document_page, see: https://github.com/OCA/knowledge/pull/24

### CODE REVIEW

**Comment by hbrunn** [comment]
It looks like you're still working on this, so I tagged this PR 'work in progress'. When you're done, could you replace the tag by 'needs review'?

**Comment by llacroix** [comment]
Anyone can restart travis for this one. The travis log is strange, I have no problem running this module with tests.

**Comment by hbrunn** [comment]
travis restarted

**Comment by bwrsandman** [comment]
Module fails to install

**Comment by max3903** [comment]
@gborelli Are you planning to fix it or shall we take over ? I would like to have it merged ASAP, as we have a lot of modules depending on it. Thanks.

**Comment by gborelli** [comment]
@max3903 Unfortunately I can't fix the issue related to the module installation.

**Comment by dreispt** [comment]
@max3903 I still think this dependency should be made optional on the `management-system` repo...

**Comment by max3903** [comment]
@dreispt you can install it and not use it (uncheck review on document page category). At least, the feature is there for those who want to use it.

**Comment by dreispt** [comment]
@max3903 I agree the feature is important and should be available.
I just don't see why it needs to be automatically installed.
It bugs me that mgmt-system basic features can't be installed if the knowledge is not also available.

**Comment by llacroix** [comment]
@dreispt we at least need the `document.page` but I agree that the document page approval might not be necessary.

**Comment by llacroix** [comment]
I'm not sure if it's posssible to solve this issue without implementing something that looks like a hack. The problem is that odoo is using workflows of modules that aren't yet loaded.

If we run a test case once, it will work without problem. On a second run, it will try to load demo data again, the demo data will trigger a workflow in "document.page.history" in the create method. The workflow will try to execute the workflow that was previously added by by document_page_approval. Unfortunately the workflow in document_page_approval is calling a method that doesn't yet exist on the document_page_history.

I implemented a small hack on my branch yet it hope there is a better way.

**Comment by bwrsandman** [comment]
Needs a rebase.

**Comment by max3903** [comment]
Resumed in #30 by @llacroix

**Pull request closed without merging**
