### PR TITLE
[FIX] document_page_approval: no "order" parameter in One2many field

### PR DESCRIPTION
**Pull request by kluna1998**
There is no order parameter in the field One2many.

### CODE REVIEW

**Review by sanchonuria — APPROVED** [review]

**Comment by etobella** [comment]
Can you rebase?

**Review by max3903 — APPROVED** [review]

**Comment by kluna1998** [comment]
> Can you rebase?

Done :blush:

**Review by etobella — APPROVED** [review]

**Comment by max3903** [comment]
@kluna1998 Can you please rebase again?

**Comment by etobella** [comment]
Problem with the copier template fixed on #375 
/ocabot merge patch

**Pull request merged**
