### PR TITLE
[FIX] No such field(s) in model email.template: body_text

### PR DESCRIPTION
**Pull request by gurneyalex**
Fix Runbot warning

### CODE REVIEW

**Comment by gurneyalex** [comment]
trying to understand why #62 builds on the wrong Odoo version on runbot. Suspecting attempted smartness in runbot in branch name analysis.

**Comment by gurneyalex** [comment]
@max3903 @pedrobaeza: I was partially wrong: it's not a branch name issue, but a graph issue: check https://github.com/savoirfairelinux/knowledge/tree/7.0-fix-no-field-body_text-in-email_template this branch is based on 8.0, not 7.0 and this is the information used by runbot to find the main branch of the project and from this the version of the server. Rebasing the branch on top of 7.0 produces a correct build.

**Comment by pedrobaeza** [comment]
Thanks for the explanation, @gurneyalex 

:+1:

**Comment by max3903** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
