### PR TITLE
[11.0][ADD] document_page_project

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
This module allow to link document pages to projects.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional tests.

**Review by JordiBForgeFlow — APPROVED** [review]
:+1:  Works like a charm!

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza ready to merge?

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
