### PR TITLE
[ADD] document_choose_directory

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by gurneyalex** [comment]
there are a few easy pep8 issues to be fixed (long lines)

a couple of tests would be welcome too.

**Comment by hbrunn** [comment]
but those derive from other modules and are fixed in #11 
What kind of test do you propose here? This is nearly exclusively about the UI

**Comment by gurneyalex** [comment]
@hbrunn: sorry, I had not paid close enough attention to the module names... 

re tests, I'm not sure what is available in the web client side. It's still worth it IMO to exercise IrAttachement.read overload and DocumentDirectory.get_candidates_for_resource.

**Comment by gurneyalex** [comment]
I reran the build manually and it is green: https://travis-ci.org/OCA/knowledge/builds/31228830 

@bwrsandman do you know why the "Failed" status in the Travis comment? the link seems to be one for anothe PR.

**Comment by hbrunn** [comment]
Back then, the flake8 step failed because it was before #11 was merged. Save for a noop-commit on this branch, I wouldn't know how to trigger a rerun of the tests in this PR

**Comment by bwrsandman** [comment]
Restarting build

**Comment by max3903** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Comment by foutoucour** [comment]
:+1:

**Pull request merged**
