### PR TITLE
[14.0][FIX] document_page_tag: change 'Tags must me unique' to 'Tags must be unique'

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
Fix a spelling error in the document_page_tag by changing 'Tags must me unique' to 'Tags must be unique'

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
@etobella could you have a look at this small one? It's fixing a typo.

THX!

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by etobella — APPROVED** [review]

**Pull request merged**
