### PR TITLE
[IMP] document_page: Add button box

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by kittiu — APPROVED** [review]

**Review by ygol — APPROVED** [review]

**Comment by max3903** [comment]
Pending decision on #250

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by marcelsavegnago — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Review by jarroyomorales — APPROVED** [review]

**Comment by etobella** [comment]
Ocabat is not runing properly... I will try again, let's see if it is enough:
/ocabot merge patch

**Comment by etobella** [comment]
image

:laughing: Ocabat!!!

**Pull request merged**
