### PR TITLE
[14.0][IMP] document_page: option to search by summary.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
[IMP] Option to search by summary.

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten

**Comment by HaraldPanten** [comment]
@etobella when you have a lot of pages, searching by content is slow, and searching by title sometimes doesn't match the information that you're trying to search.

Searching by summary is an "intermediate solution" as normally you have some words related to the title and some words related to the content.

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]

**Pull request merged**
