### PR TITLE
[15.0][IMP] document_page: add side search panel with categories.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
A search side panel with page categories is added as shown in the following screenshot.

Searchpanel_document_page_v15

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
Same as Ángel did for V14.

@etobella @pedrobaeza

**Pull request merged**
