### PR TITLE
[15.0][IMP] document_page: option to search by summary.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
Option to search by summary.
Same IMP that in v14.0 #399

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by manuelregidor** [comment]
Code review. LGTM

**Review by manuelregidor — APPROVED** [review]
Code review. LGTM.

**Pull request merged**
