### PR TITLE
[FIX] document_page: Content on 25% of the page

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by flotho** [comment]
FIX https://github.com/OCA/knowledge/issues/392

**Review by flotho — APPROVED** [review]
works like a charm :
image

**Comment by pedrobaeza** [comment]
Please run pre-commit to correct the XML style to be able to merge this.

**Comment by flotho** [comment]
Hi @max3903 , any chnce to run the precommit ?

**Comment by etobella** [comment]
I applied the same change when I made the collaborative option. Sorry. I close it as it is already solved :wink:

**Pull request closed without merging**
