### PR TITLE
[13.0][MIG] attachment_preview

### PR DESCRIPTION
**Pull request by vancouver29**
New Attempt for this old PR https://github.com/OCA/knowledge/pull/358

### CODE REVIEW

**Comment by rousseldenis** [comment]
@vancouver29 Could you preserve commit history like in the former PR ?

**Comment by vancouver29** [comment]
@rousseldenis FYI

**Review by max3903 — APPROVED** [review]

**Comment by vancouver29** [comment]
@max3903 could you please review it?

**Review by max3903 — APPROVED** [review]

**Comment by vancouver29** [comment]
@max3903 please save this PR :(

**Pull request merged**
