### PR TITLE
8.0 fix ci 2017 05 09

### PR DESCRIPTION
**Pull request by hbrunn**
@max3903 you might want to cherry pick some of these commits to 9/10

### CODE REVIEW

**Comment by max3903** [comment]
@hbrunn Sure, once squashed and merged.

**Review by max3903 — APPROVED** [review]
LGTM

**Comment by hbrunn** [comment]
I did split in in multiple commits to make the cherry picking simpler, but if you prefer one commit, I can do that, sure

**Comment by max3903** [comment]
@hbrunn Github can do it for us when we merge.

**Comment by hbrunn** [comment]
but github can't sign it with my key, and I refuse to take any responsibility for commits which are not signed by me

**Comment by hbrunn** [comment]
@max3903 anything left to do to get this merged?

**Comment by max3903** [comment]
@hbrunn Nope

**Review by dreispt — APPROVED** [review]

**Pull request merged**
