### PR TITLE
Module document_page: Improved widget and email template.

### PR DESCRIPTION
**Pull request by ghost**
## Changes
- Page history widget set to html in order to render html widget instead of plain text.
- String in email template changed from OpenERP to Odoo.

### CODE REVIEW

**Comment by max3903** [comment]
Reviewed and tested on runbot.
:+1:

**Comment by dreispt** [comment]
LGTM :+1:

**Comment by hbrunn** [comment]
@gs-clearcorp thanks for your proposal, but unfortunately, you'll have to update the template's translations too

**Comment by ghost** [comment]
> @gs-clearcorp thanks for your proposal, but unfortunately, you'll have to update the template's translations too

Hi @hbrunn!  I just updated the translations :+1:

**Comment by hbrunn** [comment]
@gs-clearcorp for this change, I think we shouldn't wait for native speakers to update the other languages. Could you change those too?

**Comment by ghost** [comment]
> @gs-clearcorp for this change, I think we shouldn't wait for native speakers to update the other languages. Could you change those too?

@hbrunn Hope this is what you expected

**Comment by hbrunn** [comment]
@gs-clearcorp thanks, even more than I expected, I just assumed the single last line containing OpenERP had to be changed. But you seem to have updated all the filed from the pot, even better, great. :+1:

**Comment by ghost** [comment]
> @gs-clearcorp thanks, even more than I expected, I just assumed the single last line containing OpenERP had to be changed. But you seem to have updated all the filed from the pot, even better, great.

Thanks :+1:

**Pull request merged**
