### PR TITLE
[17.0][MIG] document_page_group: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 156912
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/knowledge/issues/442

### CODE REVIEW

**Review by lbarry-apsl — APPROVED** [review]
Tested on the Runboat, works well.

**Review by miquelpascual — APPROVED** [review]
LGTM!

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Pull request merged**
