### PR TITLE
[16.0][FIX] document_url: Migration was not done properly

### LINKED ISSUE #413: Document_URL not available
## Module
Document_URL : https://github.com/OCA/knowledge/tree/16.0/document_url

## Describe the bug
Cannot find the feature.   Didn't see the wizard once we click on paper clip. 

## To Reproduce
**Affected versions**: launch a runbot and try to use document_url module

Open the form view of an object (Example: Customer Invoice INV/2019/0007).
Go to the chatter and click on the attached icon.
"Click Add URL link."   Their is not "Add URL Link" 

**Expected behavior**
Open the form view of an object (Example: Customer Invoice INV/2019/0007).
Go to the chatter and click on the attached icon.
Click Add URL link.
Fill the wizard fields and click on Add button.
You will see a new URL attachment in the set of attachments related to the object.

**Additional context**
V16

### PR DESCRIPTION
**Pull request by etobella**
This was not working.
Now it should work properly....

@FernandoRomera @AntoniRomera @MRomeera

### CODE REVIEW

**Comment by etobella** [comment]
Fixes #413

@bealdav

**Comment by PaulGoubert** [comment]
Thank you very much @etobella

**Comment by bealdav** [comment]
Hi @etobella thanks a lot for this PR

It works really well with chrome, but fails with `firefox 113.0.2` on `Linux`

Firefox doesn't open wizard when you click on `Add Url`

EDIT : maybe we could mention in README/usage that `Add Url` button is only displayed when an attachment exists (not an url link)

**Review by AntoniRomera — APPROVED** [review]
LGTM

**Review by victoralmau — APPROVED** [review]

**Comment by bealdav** [comment]
@victoralmau @AntoniRomera Did you tested on runboat with firefox ?

**Comment by victoralmau** [comment]
> @victoralmau @AntoniRomera Did you tested on runboat with firefox ?

Yes, it is tested and it works correctly.

**Comment by pedrobaeza** [comment]
I think for now is enough to merge this and fix the main problem:

/ocabot merge patch

@bealdav please check if you have any Firefox plugin interacting.

**Comment by bealdav** [comment]
Thanks, I have identify with firefox when it works and when it doesn't works

image

it works, sidebar, chatter is below


image

It doesn't works when I click on the button with the sidebar is on the right



It's not related to addons because it's the same behavior  with another empty firefox profile


However thanks a lot for this fix. I can live with this identified problem ;-)

**Comment by pedrobaeza** [comment]
What about uninstalling web_chatter_position?

**Comment by bealdav** [comment]
web_chatter_position, is not installed, I suppose it's a native feature in Odoo 16 now to make chatter responsive

**Comment by bealdav** [comment]
Thanks a lot for taking care of it @pedrobaeza

**Comment by PaulGoubert** [comment]
Thank you all for this work.
I just tested on Chrome and I see exactly the same behaviour as @bealdav.
Impossible to click on "add url" once is on the right side, but working fine when it's down.
At least, their is a way to make it work. 

Once again, thank you @etobella @pedrobaeza

**Pull request merged**
