### PR TITLE
[MIG] knowledge: Migration to 14.0

### PR DESCRIPTION
**Pull request by dzungtran89**

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
Code review and Functional Test done. LGTM

**Comment by fshah-initos** [comment]
It would be great if somone could add reviews here so we can merge this PR.

**Comment by fshah-initos** [comment]
can somone please review this PR?

**Comment by fshah-initos** [comment]
It would be great if we could get the reviews here so that our PR can be merged.

**Comment by fshah-initos** [comment]
Is it possible to merge the PR?

**Review by victoralmau — APPROVED** [review]

**Comment by fshah-initos** [comment]
Maintainers please merge this PR.

**Comment by desdelinux** [comment]
Maintainers please merge this PR.

**Comment by fshah-initos** [comment]
It would be nice if maintaines merge this PR

**Comment by victoralmau** [comment]
ping @pedrobaeza it's ready to merge, right?

**Pull request merged**
