### PR TITLE
[FIX] - document-page-approval: Fixes #60 url not valid when website module is installed.

### LINKED ISSUE #60: Module document_page_approval: URL does not match when website is installed.
The url does not work if website module is installed
http://localhost:8001/#db=test&id=1&view_type=form&model=document.page.history

It needs to be
http://localhost:8001/web#db=test&id=1&view_type=form&model=document.page.history
with /web

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think there's a method to get the URL prefix to avoid this manual adjustment. Can you please check it?

**Comment by ghost** [comment]
> I think there's a method to get the URL prefix to avoid this manual adjustment. Can you please check it?

Hi @pedrobaeza 

As far as I know Odoo does it like this in auth_signup module res_users.py

``` python
base_url = self.pool.get('ir.config_parameter').get_param(cr, uid, 'web.base.url')
...
res[partner.id] = urljoin(base_url, "/web/%s?%s" % (route, werkzeug.url_encode(query)))
```

Do you know where can I find that method to avoid including it manually?

**Comment by pedrobaeza** [comment]
OK, I thought it exists. Then :+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
