### PR TITLE
[MIG] document_page: Migration to 17.0.

### PR DESCRIPTION
**Pull request by Tisho99**
T-5738

### CODE REVIEW

**Comment by Tisho99** [comment]
@HaraldPanten @ValentinVinagre

The PR is ready.

I don't think the code coverage should be improved, it decreases because before it was almos 100%

**Review by HaraldPanten — APPROVED** [review]
Functional review LGTM.

@etobella @ValentinVinagre

**Comment by etobella** [comment]
Collaborative is not working on runboat. Can you check?

**Comment by HaraldPanten** [comment]
> Collaborative is not working on runboat. Can you check?

Do you mean Documents approval, right?

**Comment by etobella** [comment]
Collaborative is when two users see the work done by the other in real life.

https://github.com/OCA/knowledge/pull/394

**Comment by ValentinVinagre** [comment]
@etobella I have tested it and it works correctly. You just have to indicate in the "demo" user that they have to be an editor in "documents knowledge".
image
image

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Comment by ValentinVinagre** [comment]
> /ocabot merge nobump

yuhu 😄

**Pull request merged**
