### PR TITLE
[13.0][MIG] document_page_reference

### PR DESCRIPTION
**Pull request by jarroyomorales**
Migration of document_page_reference to v13.

@etobella

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1: No major changes

**Review by etobella — CHANGES_REQUESTED** [review]
When doing the functional review I found that when accessing the related reference it goes to the view of configuration:

peek knowledge issue

**Comment by jarroyomorales** [comment]
@etobella Solved! Also checked  if the same happens in v12.0 but it seems to be working fine there.

**Review by etobella — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
