### PR TITLE
Fix TypeError: function lambda at 0x7f1f2cb562a8 is not JSON serializ…

### LINKED ISSUE #54: [8.0] TypeError: function lambda at 0x7f1f2cb562a8 is not JSON serializable
after installed, when click menu Marketing-MassMailing, the message pop

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    return self._json_response(result)
  File "/opt/odoo/openerp/http.py", line 519, in _json_response
    body = simplejson.dumps(response)
  File "/home/odoo/odoo/lib/python2.7/site-packages/simplejson/__init__.py", line 370, in dumps
    return _default_encoder.encode(obj)
  File "/home/odoo/odoo/lib/python2.7/site-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/odoo/odoo/lib/python2.7/site-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/home/odoo/odoo/lib/python2.7/site-packages/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x7f1f2cb562a8> is not JSON serializable

### PR DESCRIPTION
**Pull request by naousse**
…able

Fixes #54

### CODE REVIEW

**Comment by hbrunn** [comment]
@naousse do you have an idea what the removed code was supposed to do in the first place?

**Comment by max3903** [comment]
@hbrunn We don't. It's a module from Odoo SA with not much explanation.

**Comment by hbrunn** [comment]
okay, someone/something will scream if we need it :+1:

**Comment by max3903** [comment]
:+1:

**Comment by Whytehorse** [comment]
This is still a bug in 8.0. Removing module document_page is a workaround but not a solution.

**Comment by max3903** [comment]
@Whytehorse This is the pull request on version 9. Have you tested on that version as well?
Otherwise, here is the pull request for version 8: #82

**Comment by max3903** [comment]
@Whytehorse I just tested on version 8 and 9 and everything works as expected. Make sure to update your code.

**Comment by Whytehorse** [comment]
So I need to update OCA Knowledge module to get the fix? Is it part of the Odoo 8.0 nightly or separate?

**Comment by max3903** [comment]
@Whytehorse Yes, you need to update the knowledge module to get the fix. It is separate.

**Comment by Whytehorse** [comment]
That fixed it for me. THANK YOU!!!! I LOVE YOU!!! SMOOCH. hehe

**Pull request merged**
