### PR TITLE
[14.0][IMP] document_page: add side search panel with categories.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
A search side panel with page categories is added as shown in the following screenshot.

Captura de pantalla de 2022-04-29 11-59-04

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM 👍 

Let's see what does Enric think about these improvements.

@etobella

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok

**Comment by HaraldPanten** [comment]
> /ocabot merge minor

THX!

**Pull request merged**
