### PR TITLE
[IMP]document_page_tag: Color column in tag tree view

### PR DESCRIPTION
**Pull request by manuelregidor**
Add the color column to the tag tree view.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by etobella — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
Fast tracking this one as it is really simple

**Pull request merged**
