### PR TITLE
[16.0]ADD Partner field

### PR DESCRIPTION
**Pull request by flotho**
IMP: small display improvements

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This doesn't have too much sense for a general module IMO. Do this in a separate module.

**Comment by flotho** [comment]
Hi @pedrobaeza thanks for your comment.
I'll separate the behaviour in another module.
FMI, what criteria makes you consider that it's not relevent to have this in document page?

**Comment by pedrobaeza** [comment]
This module is for creating document pages, normally for your own company as documentation, management system, etc. On that context, a partner field is not adding value and being misleading.

And another thing: if you add things in an existing module, the label should be `[IMP]`, not `[ADD]`. The second one is for adding a new module. If not, being philosophical, everything will be `[ADD]`, even a fix, as it's adding value to the module, hehe.

**Comment by flotho** [comment]
hum, thanks for the feedback @pedrobaeza 
Regarding the functionnal part, loks like your point of view will lead us to a business requirements insted of a partner field on this module.
My idea was : 

- find easily documentation relevant to a specific customer
- share easily this documentation on the portal

What would be your recommendation ?

regards

**Comment by pedrobaeza** [comment]
For the second point, maybe it's better to use `dms` module. If not, you should add the portal view page visualization with permissions.

**Comment by flotho** [comment]
thanks for sharing your advices.
Regards

**Pull request closed without merging**
