### PR TITLE
[17.0][MIG] document_knowledge: Migration to 17.0

### PR DESCRIPTION
**Pull request by m1k3lm**
/ocabot migration document_knowledge

### CODE REVIEW

**Review by yaseentai — APPROVED** [review]

**Comment by mgc-adhoc** [comment]
LGTM Functional +1 @pedrobaeza @yaseentai

**Review by rov-adhoc — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@m1k3lm please split pre-commit commit from the migration itself, and also squash latest administrative commits into the generating one.

image

**Comment by m1k3lm** [comment]
@pedrobaeza not sure If I got what you meant, let see if it is ok like this.

**Comment by pedrobaeza** [comment]
There's still no 2 commits, one for pre-commit stuff, and another for the migration itself. See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch for the original method to follow.

**Comment by m1k3lm** [comment]
Sorry, @pedrobaeza I still don't understand what you mean. [959d9bc](https://github.com/OCA/knowledge/pull/447/commits/959d9bc72422714853c57060924c69cee8b81682) is the migration itself all the previous ones are what you call  "pre-commit stuff"? If I sqash all of them into one the commit history would get lost.

**Comment by pedrobaeza** [comment]
You didn't follow the migration procedure, splitting the stuff resulting of running `pre-commit run -a` in a separate commit. Please review the technical procedure carefully.

**Comment by pedrobaeza** [comment]
Now the commits are mostly correct (the version shouldn't be changed in the pre-commit commit), but you should also switch the configuration view (`res.config.settings`) according the instructions in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#tasks-to-do-in-the-migration

**Comment by m1k3lm** [comment]
I did not change anything in the pre-commit, just run `pre-commit run -a` and commit. Version is changed [here](https://github.com/OCA/knowledge/pull/447/commits/3484421afd42e13afa30bb481f9d41c127869064#diff-bf3c9876716cc45d5d579a36f306db72539ebd797dcaecfb565df9866607b42aL5)
I've made the changes to the view (`res.config.settings`)

Thanks a lot for your time @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Thanks for the efforts:

/ocabot merge nobump

**Comment by jjscarafia** [comment]
@pedrobaeza can you send to merge again? Don´t know why but oca bot didn't merge it

**Comment by pedrobaeza** [comment]
System glitches...

/ocabot merge nobump

**Pull request merged**
