### PR TITLE
[14.0][IMP] document_page_tag: add side search panel with tags.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
A search side panel with tags is added as shown in the following screenshot.

Searchpanel_Tags

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
A simple but attractive improvement. You'll like it @etobella

**Review by etobella — APPROVED** [review]
Thanks! It makes total sense :smile:

**Pull request merged**
