### PR TITLE
[11.0][MIG] document_page  Migration

### PR DESCRIPTION
**Pull request by jalzaga**
Depends on:

- [x]  knowledge #149

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks, this is better. Please check Travis status, and you should squash adjacent "OCA Transbot..." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by pedrobaeza** [comment]
Please rebase now that the dependency is merged

**Comment by MiquelRForgeFlow** [comment]
Could you also include https://github.com/OCA/knowledge/pull/168?

**Review by GavyMG — COMMENTED** [review]
This field is deprecated https://github.com/OCA/knowledge/pull/157/files/d2b5700c6bd9dc7b20d579d88ff89e97f0614220#diff-a0497a23909cc7152bb18cb7271291acR41

**Comment by GavyMG** [comment]
I continue this PR here https://github.com/OCA/knowledge/pull/173

**Comment by pedrobaeza** [comment]
Superseeded by #173

**Pull request closed without merging**
