### PR TITLE
[ADD] document_tag

### PR DESCRIPTION
**Pull request by max3903**
Depends on:
- [x] #251

### CODE REVIEW

**Review by ygol — COMMENTED** [review]
wouldn't it make sense to have the tag directly added the document_page? do we need a separate module?

**Comment by kittiu** [comment]
I agree with @ygol to have this part of page.

**Comment by max3903** [comment]
@OCA/document-maintainers

**Comment by ivantodorovich** [comment]
I agree it makes more sense to include this in `document_page` module, than having a separate module.
In any case thanks @max3903 for this :)

**Comment by etobella** [comment]
Which is the sense of this module if there is already `document_page_tag` on 12.0 that has a similar behavior?

https://github.com/OCA/knowledge/tree/12.0/document_page_tag

The only missing thing is company and parent-child behavior, this can be added easily on the original module if it is needed

**Comment by ivantodorovich** [comment]
> Which is the sense of this module if there is already `document_page_tag` on 12.0 that has a similar behavior?
> 
> https://github.com/OCA/knowledge/tree/12.0/document_page_tag
> 
> The only missing thing is company and parent-child behavior, this can be added easily on the original module if it is needed

Indeed, but in any case I'm in favour of merging that feature into `document_page`. That's easier to maintain than a bunch of small modules, specially for non invasive features like this one

**Comment by etobella** [comment]
Ok then! @max3903 Can you check it?

**Comment by max3903** [comment]
@etobella Sorry guys, I don't have time for this.

**Pull request closed without merging**
