### PR TITLE
[MIG][14.0] document_page_approval

### PR DESCRIPTION
**Pull request by llabusch93**
This PR is a continuation of [PR 286](https://github.com/OCA/knowledge/pull/286).

### CODE REVIEW

**Review by gaikaz — APPROVED** [review]
LGTM

**Comment by FernandoRomera** [comment]
@llabusch93 
Can you do rebase to lunch new build system?

**Comment by llabusch93** [comment]
Hello @FernandoRomera,

done.

**Review by FernandoRomera — APPROVED** [review]

**Comment by llabusch93** [comment]
Hello @FernandoRomera and @gaikaz 

you both approved, perfect thanks. So when this will get merged then?

**Review by AntoniRomera — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@etobella Can you merge?

**Review by etobella — APPROVED** [review]

**Pull request merged**
