### PR TITLE
Slovenian translations added and updated

### PR DESCRIPTION
**Pull request by sysadminmatmoz**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Seems OK

:+1:

**Comment by max3903** [comment]
:+1:

**Comment by yvaucher** [comment]
@sysadminmatmoz It seems you have extra commits can you rebase ?

**Comment by sysadminmatmoz** [comment]
Done

**Comment by sysadminmatmoz** [comment]
Nah, with the last rebase I messed the my git and have no idea what have I done :) I'll look into it when I'm back at my office.

**Comment by sysadminmatmoz** [comment]
All checks passed and there are only translations in the commit. Is it ok or are there still pending issues?

**Comment by pedrobaeza** [comment]
There are still extra commits in the PR, with code in them. You need to properly rebase.

**Comment by sysadminmatmoz** [comment]
I just can't find them!? The only diff I see are the po files.

**Comment by sysadminmatmoz** [comment]
I'll do the simplest thing - git reset and fresh start with a new commit and PR:)

**Comment by pedrobaeza** [comment]
There's no need of a new PR: just overwrite this branch with -f option, but if you are not very used with git, start again with all is the best option.

**Comment by sysadminmatmoz** [comment]
I used this repo as a submodule - it's just faster to delete it than clean it. I made another PR.

**Comment by pedrobaeza** [comment]
Superseeded by #48

**Pull request closed without merging**
