### PR TITLE
Translations sync with templates

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
Nothing much, just cleaning my translations infrastructure and correcting the translations templates mistakes I find out in all the OCA repos

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Technically :+1:

Curious that this also include an italian translation...

**Comment by sysadminmatmoz** [comment]
Hehe, I'm bilingual, and lots of my clients are Italians.

**Comment by pedrobaeza** [comment]
You're very versatile. That's good! Do you have also programming or functional skills? It would be good to see you around making PRs, or making reviews of other PRs trying them on runbot.

**Comment by sysadminmatmoz** [comment]
We can always talk about it :smile: ... but not here :lock: I'm not a "born" coder, but I do hack a little, I'm not a professional IT guy, but I am a computer nerd, I don't know everything but I certainly can learn everything (and fast)... :smiley: ... and I'm not the youngest but still young at heart

**Comment by sysadminmatmoz** [comment]
Just to be thorough, I synced all the templates and all the languages with the actual build.

**Comment by pedrobaeza** [comment]
Yeah, I know, but this is a mistake by Avanzosc to put that files at first instance.

**Comment by max3903** [comment]
:+1:

**Pull request merged**
