### PR TITLE
[IMP] document_ocr: handle invalid data in attachments gracefully

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by gurneyalex** [comment]
hello I think #217 will help getting a green build on this one.

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
#217 is merged. Can you rebase your PR?

**Comment by hbrunn** [comment]
done

**Review by NL66278 — APPROVED** [review]

**Comment by etobella** [comment]
Travis failed randomly, so trying again /ocabot merge patch

**Pull request merged**
