### PR TITLE
[MIG] 14.0 knowledge and document_page

### PR DESCRIPTION
**Pull request by PierrickBrun**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM Functional test

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test.

**Comment by llabusch93** [comment]
Hello guys,
when this will be merged?

**Comment by PierrickBrun** [comment]
Hi @llabusch93 The PR needs 2 approvals before being merged so it would be quicker if you review it :smile:

**Review by ozono — APPROVED** [review]
Tested. LGTM

**Comment by YvanDotet** [comment]
Hello
Is it ready to merge in the 14.0 branch ?
Thank you.

**Review by marcelsavegnago — APPROVED** [review]

**Comment by gurneyalex** [comment]
modules available in 14.0

**Pull request closed without merging**
