### PR TITLE
fix attachments_to_filesystem

### PR DESCRIPTION
**Pull request by luc-demeyer**
correction for https://github.com/OCA/knowledge/issues/135

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What about Travis?

**Comment by lasley** [comment]
And maybe a unit test to cover this, seeing as it already bit us in the ass once?

**Comment by luc-demeyer** [comment]
The travis failure is unrelated to this fix. 
Adding a unit test would of course be a lot better but the question is who has time to do it.
In the meanwhile we should merge this fix or fully revert PR #129 because now we have a broken module which is worse.

**Review by pedrobaeza — APPROVED** [review]
Well, it was broken before that PR also. Travis is unrelated indeed.

**Review by lasley — APPROVED** [review]

**Comment by hbrunn** [comment]
tests will be helpful anyways, I only merged this without them because it fixes a problem

**Pull request merged**
