### PR TITLE
[IMP][10.0][document_page_approval] Change Requests and workflow improvements on documents (#155)

### PR DESCRIPTION
**Pull request by ivantodorovich**
Mig #155 to `10.0` (2/2)

Depends on https://github.com/OCA/knowledge/pull/159

### CODE REVIEW

**Comment by max3903** [comment]
@ivantodorovich Yes, `document_page_approval` tests are failing, that's fine, but `document_page`ones should pass: https://travis-ci.org/OCA/knowledge/jobs/366149729#L823

**Review by dreispt — APPROVED** [review]
I'm concerned about keeping the workflow engine, but that's only blocking for v11.
LGTM.

**Comment by max3903** [comment]
@ivantodorovich Can you please rebase?

**Comment by ivantodorovich** [comment]
Done!

**Comment by ivantodorovich** [comment]
I'm concerned that, if this does not get merged, `document_page_approval` will be failing for anyone cloning this branch, because https://github.com/OCA/knowledge/pull/159 is already merged

**Review by max3903 — APPROVED** [review]

**Pull request merged**
