### PR TITLE
[12.0][MIG] attachment_preview

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Try to enter the runbot you will get an style error: 

```
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

The "--no-js" argument is deprecated, as inline JavaScript is disabled by default. Use "--js" to enable inline JavaScript (not recommended).
NameError: variable @gray-lighter-dark is undefined in - on line 48, column 32:
47         background-color: #FFF;
48         border-left: 1px solid @gray-lighter-dark;
49 
(...)
```

**Comment by MiquelRForgeFlow** [comment]
@lreficent solved style errors :)

**Comment by tarteo** [comment]
The iframe and controls are located at the bottom of the chatter:
image
How do I open the preview?
image

**Review by tarteo — CHANGES_REQUESTED** [review]
The iframe and controls are located at the bottom of the chatter:
image
How do I open the preview?
image

**Comment by MiquelRForgeFlow** [comment]
@tarteo please, could you better suggest me code changes?

**Comment by tarteo** [comment]
@mreficent Why? Code looks good to me maybe you can take a look at the jslint errors.

**Comment by MiquelRForgeFlow** [comment]
@tarteo solved the issue, I had to update to BS4. Ready to review!

**Review by astirpe — APPROVED** [review]
Tested locally :+1:

**Comment by tarteo** [comment]
@mreficent How do I open the split preview screen? I can only open the standard Odoo 12.0 preview.

1.
image

2.
image

**Review by astirpe — CHANGES_REQUESTED** [review]
Sorry, I just noticed that the preview of the images is a feature already present in Odoo Community 12.0. So my previous test was not correct.
What is this module providing more than the standard Odoo?

**Comment by svalaeys** [comment]
Does the standard Odoo functionality allow for split-screen viewing the way this one does? That is in my opinion the most important contribution of this module.

**Comment by JordiBForgeFlow** [comment]
@mreficent @tarteo @svalaeys @astirpe as it is now, this PR simply does not work. And what is visible is the standard V12 preview. So I'm closing the PR for now.

**Comment by astirpe** [comment]
For the ones who are interested, here it is the `attachment_preview` for V12: https://github.com/OCA/knowledge/pull/221

**Pull request closed without merging**
