### PR TITLE
[12.0][FIX] document_page_approval: fix strings

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@ivantodorovich can you review please ?

**Review by jpcarassato — APPROVED** [review]
OK

**Comment by marcelsavegnago** [comment]
@OCA/management-systems-maintainers can you review please?

**Comment by ivantodorovich** [comment]
Sorry for the delay. Somehow I missed this notification.

pot files are generated by travis, and AFAIK modifying them manually can potentially cause issues with weblate.

What's the point of this change?

**Comment by marcelsavegnago** [comment]
@ivantodorovich 
document_page_approval/i18n/document_page_approval.pot:1: [E7912(po-syntax-error), ]  Syntax error in po file (line 266)

You're right .. I'll check and correct it in the code.

**Review by ivantodorovich — CHANGES_REQUESTED** [review]
You shouldn't modifity the `pot` file, as this is going to be generated and updated by travis. Anyway, it looks like your changes are in sync so I guess it's ok :+1:

**Review by ivantodorovich — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @ivantodorovich

**Comment by ivantodorovich** [comment]
I already approved, although I'm not maintainer of this repo so I can't merge it 😅

**Comment by marcelsavegnago** [comment]
> I already approved, although I'm not maintainer of this repo so I can't merge it 😅

@ivantodorovich 😄  sorry and thanks 

@max3903 you can help ?

**Review by etobella — APPROVED** [review]

**Pull request merged**
