### PR TITLE
[ADD]document_page_access_group: Add access groups to document pages

### PR DESCRIPTION
**Pull request by manuelregidor**
New module to select which users groups have access to document pages.

document_page_access_group

If no groups are selected in a document, all users with access to documents can access this document.

Only users that belong to the 'Knowledge / Manager' group can manage access groups to documents.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
Functional review. Works like a charm.

**Review by antoniocanovas — APPROVED** [review]
Fictional review ok

**Review by andhit-r — APPROVED** [review]
Functional review :heavy_check_mark:

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
