### PR TITLE
WIP -- [MIG][10.0] Change Requests and workflow improvements on documents (#155)

### PR DESCRIPTION
**Pull request by ivantodorovich**
Mig  #155 to `10.0'

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Ready

**Comment by max3903** [comment]
@ivantodorovich Please split the pull request. One for each module.

**Comment by ivantodorovich** [comment]
Sure! Will do it tomorrow, though.

**Comment by ivantodorovich** [comment]
Closed in favour of https://github.com/OCA/knowledge/pull/159 and https://github.com/OCA/knowledge/pull/160

**Pull request closed without merging**
