### PR TITLE
[13.0][MIG]document_page_tag

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
Functional review LGTM.

@etobella @joao-p-marques could you merge?

THX!

**Review by etobella — APPROVED** [review]

**Pull request merged**
