### PR TITLE
[13.0][MIG] attachment_zipped_download

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
CC @ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Technical review LGTM

You might need to review tests, because one is failing

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please fw-port it to upper versions.

**Comment by pedrobaeza** [comment]
Sorry, incorrect PR, aborting merge.

**Comment by pedrobaeza** [comment]
Please fix the tests to be able to merge this.

**Pull request closed without merging**
