### PR TITLE
[FIX] No such field(s) in model email.template: body_text

### PR DESCRIPTION
**Pull request by max3903**
Fix Runbot warning

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Uhm, very curious that the module `document_page` doesn't get detected. Any clues?

**Comment by max3903** [comment]
@pedrobaeza Runbot ran this branch with version 8.0:

```
2015-08-23 18:55:20,151 29003 INFO ? openerp: OpenERP version 8.0
```

**Comment by pedrobaeza** [comment]
I have launched a rebuilt to see again...

**Comment by max3903** [comment]
Still

```
2015-08-23 21:33:00,964 26921 INFO ? openerp: OpenERP version 8.0
```

https://runbot2.odoo-community.org/runbot/static/build/3113548-62-12d2e5/logs/job_10_test_base.txt

**Comment by pedrobaeza** [comment]
I definitely don't have any clue. Let's see if @gurneyalex can figure out why is this happening.

**Comment by gurneyalex** [comment]
explanation provided on #64

**Comment by pedrobaeza** [comment]
Superseeded by #64

**Pull request closed without merging**
