### PR TITLE
[15.0][IMP] document_page: copy document function.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
The copy function is modified to create a copy named original_name+(copy) and with the same content.
Same as PR #351 v14.0

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Pull request merged**
