### PR TITLE
[16.0] [MIG] knowledge

### PR DESCRIPTION
**Pull request by marielejeune**
Migrated to version 16.0

TODO: change module name, since knowledge is now a distinct Odoo module.

### CODE REVIEW

**Comment by marielejeune** [comment]
https://github.com/OCA/knowledge/issues/366

**Comment by pedrobaeza** [comment]
For having the whole history with the new name for later migrations (in v17, v18...), please execute this command:

```bash
git filter-branch --tree-filter 'if [ -d old_module_name ]; then mv old_module_name new_module_name; fi' HEAD
```

**Comment by marielejeune** [comment]
@pedrobaeza for changing module name, do you see something more to do than running https://github.com/OCA/openupgradelib/blob/94762d1a5a4172b680a7e019fe4d7db44b2bf7af/openupgradelib/openupgrade.py#L1529 in a pre-migration script?

**Comment by pedrobaeza** [comment]
Hi, @marielejeune 

That's only needed when you are migrating from 15.0 to 16.0, but not for the module migration itself. On OpenUpgrade, we add all the renamings/mergings in this file:

https://github.com/OCA/OpenUpgrade/blob/15.0/openupgrade_scripts/apriori.py

and the method you mentioned is called from `base` module migration script.

**Comment by pedrobaeza** [comment]
Good name selected. Please remember to rename whole commit history.

**Comment by sbidoul** [comment]
> Please remember to rename whole commit history.

Ow, that is surprising. I understand the reason but... one more thing to add to my list of downsides of our current migration approach ;)

@sebalix as you work on oca-port, what do you think of this idea of renaming a module in past commits when migrating? Have you already thought about module renaming in oca-port?

**Comment by pedrobaeza** [comment]
The problem will be similar when reusing the same branches, as git wont' find references before the renaming, so I think this is even better, as you have the occasion to accommodate the history for this case.

**Comment by marielejeune** [comment]
Hi @pedrobaeza, I'm not sure to understand what this command should do?
`git filter-branch --tree-filter 'if [ -d old_module_name ]; then mv old_module_name new_module_name; fi' HEAD`

I launched it locally but apart new commits sha, I don't see any difference.

**Comment by pedrobaeza** [comment]
You need to change `old_module_name` and `new_module_name` by the corresponding ones: `knowledge` and `document_knowledge`.

**Comment by marielejeune** [comment]
Yes, that was done

**Comment by pedrobaeza** [comment]
Well, if you inspect a commit before the last one, check if now the module directory has the new name.

**Comment by pedrobaeza** [comment]
You can forced push it here also to be checked.

**Comment by pedrobaeza** [comment]
Oh, I think you need to do a rebase over origin/16.0 before...

**Comment by sebalix** [comment]
@sbidoul I thought about a  `--rename-to` option but nothing done right now. I didn't know we should rename the module also in the past commits.
I created https://github.com/OCA/oca-port/issues/11

**Comment by sbidoul** [comment]
> I didn't know we should rename the module

Well I'm not sure we should either, TBH.

**Pull request closed without merging**
