### PR TITLE
[MIG] from 8.0 to 9.0 document_url

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
- bump version to 9.0.1.0.0 and make it installable
- Update JS structure
- Add css in order to be compliant with odoo style
- Add a README.rst and OCA conventions
- Improve selector
- add fr.po for fr translation

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I have tested and seems good. I think it's better to open the link in a new window, don't you think?

**Comment by JonathanNEMRY** [comment]
Yes that could be a good thing!...I noticed that server' tests failed...with `test_document_page_history_workflow` do you have any idea about this?

**Comment by pedrobaeza** [comment]
There's an open issue here: https://github.com/OCA/knowledge/issues/85

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@JonathanNEMRY, can you please make that the URL opens in a new window?

**Comment by JonathanNEMRY** [comment]
Hi @pedrobaeza I will take a look on this one ASAP

**Comment by dreispt** [comment]
LGTM :+1:

**Comment by rafaelbn** [comment]
Hi @JonathanNEMRY thanks for this contribution. Just URL opens in a new window and this PR can be merged! :smile:

**Comment by JonathanNEMRY** [comment]
Hi everyone, sorry for the wait I finally took some time to improve this module migration with the last request: open it into a new window. Hope this is OK now :smile:

**Comment by pedrobaeza** [comment]
Working great, thanks! :+1:

**Pull request merged**
