### PR TITLE
[14.0][MIG] attachment_category

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Code review and functional review with runbot

image

**Review by PierrickBrun — APPROVED** [review]
functional review OK.

I had errors in pre-commit because `website` is not present in manifest. I guess it did not trigger because it ran on an older version when you created the PR but it should block the merge with OCAbot.

**Review by ivantodorovich — APPROVED** [review]

**Comment by cvinh** [comment]
@gurneyalex could you please try to merge that PR again ?
Thank you

**Comment by gurneyalex** [comment]
@rousseldenis could you check the pre-commit errors?

**Comment by rousseldenis** [comment]
@gurneyalex I've rebased

**Pull request merged**
