### PR TITLE
[FIX] flake8

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by gurneyalex** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Do you think it deserves to remake 8.0 branch with all 7.0 modules with PEP8 fixed moved again to `__unported__`?

**Comment by hbrunn** [comment]
why not simply overwrite the addons in 8.0/**unported** with the code from 7.0?

**Comment by pedrobaeza** [comment]
OK, I'll make the PR.

**Comment by pedrobaeza** [comment]
Done: https://github.com/OCA/knowledge/pull/13

**Pull request merged**
