### PR TITLE
[12.0]IMP: Add single menu for content browsing

### PR DESCRIPTION
**Pull request by flotho**
* Categories and content are now available and browsable in a single menu.
* Navigation helps user to find content easily
* Cleanups for pylint and flake

superseeds https://github.com/OCA/knowledge/pull/318

### CODE REVIEW

**Comment by flotho** [comment]
Hi @pedrobaeza , @yavuzavci , this one is ready for review, green and obvisously more simple to read.

Thanks

**Comment by flotho** [comment]
any chance to be reviewed ?

**Comment by flotho** [comment]
@jacob88 maybe you could have a look / review to my improvements I'll do the same to your PR #320

**Comment by flotho** [comment]
I suppose that friday is OCA merge day so I try an additionnal ping @pedrobaeza @yavuzavci and @jacob88 to be reviewed on this one.
Thanks

**Comment by flotho** [comment]
Hi,  @gurneyalex @max3903 @hbrunn @lmignon @etobella , I contact you as team members of this repo.
Is it possible to be reviewed?

Thanks

**Comment by lmignon** [comment]
@flotho It's very difficult to review since cleanup and changes are all into the same commit...

**Review by gurneyalex — APPROVED** [review]

**Comment by flotho** [comment]
> @flotho It's very difficult to review since cleanup and changes are all into the same commit...

you're right I understand. I'll try my best ASAP

**Review by lmignon — APPROVED** [review]

**Comment by flotho** [comment]
thanks to both of you, I promise to work better next time and separate properly commits

**Comment by lmignon** [comment]
Thank you to you for your contribution @flotho !

**Comment by flotho** [comment]
do you enjoy this feature @lmignon ?

**Comment by lmignon** [comment]
Unfortunately, I cannot answer the question. It is a module that I do not use.

**Comment by flotho** [comment]
could you point me the proper way to port this in netx release please ?

**Comment by lmignon** [comment]
@flotho The migration process is explained [here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0)

**Pull request merged**
